import type { StatDelta, SimHook, TeamModifier } from './effects';

/**
 * Signature abilities for the Legendary (real NBA) players. Each bends one rule
 * the way the real player did. Three contribution channels, all optional:
 *  - selfDelta: a flat self-buff, baked into the player's own stats by
 *    effectivePlayers (apply-effects.ts).
 *  - teamAura: a flat TeamModifier fragment contributed to the player's team.
 *  - hooks: conditional sim-time rule-benders contributed to the team modifier.
 *
 * Most legends are felt through their re-rated 10-stat line; the ability is the
 * extra "that's why he's a legend" spike. Magnitudes sit at the top of the
 * synergy band (2-3 rating points) per the balance anchor (+1 ~ +3.2% make on
 * the 6-20 scale).
 */
export interface Ability {
  id: string;
  /** Display name for the gold nameplate / scout line. */
  name: string;
  /** One-line "rule bent" description. */
  blurb: string;
  selfDelta?: StatDelta;
  teamAura?: Partial<TeamModifier>;
  hooks?: SimHook[];
}

export const ABILITIES: Record<string, Ability> = {
  flu_game: {
    id: 'flu_game',
    name: 'Flu Game',
    blurb: 'Takes over the fourth quarter: +6 to scoring and perimeter D.',
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { inside: 6, outside: 6, perimeterD: 6 } }],
  },
  mamba: {
    id: 'mamba',
    name: 'Mamba Mentality',
    blurb: 'A pure scorer who rises in crunch time: +4 outside, +4 clutch in Q4.',
    selfDelta: { outside: 2 },
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { outside: 4, clutch: 4 } }],
  },
  dame_time: {
    id: 'dame_time',
    name: 'Dame Time',
    blurb: 'Logo-range daggers when it matters: +6 outside in the fourth.',
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { outside: 6 } }],
  },
  cold_blooded: {
    id: 'cold_blooded',
    name: 'Cold Blooded',
    blurb: 'Never rattled: +2 outside, +2 clutch.',
    selfDelta: { outside: 2, clutch: 2 },
  },
  sky_hook: {
    id: 'sky_hook',
    name: 'Skyhook',
    blurb: 'An unblockable signature: +2 inside.',
    selfDelta: { inside: 2 },
  },
  rim_wall: {
    id: 'rim_wall',
    name: 'The Wall',
    blurb: 'Anchors the paint: +2 interior D, and caps the opponent\'s finishing.',
    selfDelta: { interiorD: 2 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'inside', mult: 0.8, when: 'defense' }],
  },
  diesel: {
    id: 'diesel',
    name: 'Diesel',
    blurb: 'Unstoppable in the post: halves your interior D unless you double-team.',
    hooks: [{ kind: 'opponentRatingMult', stat: 'interiorD', mult: 0.5, when: 'offense', unlessDoubled: true }],
  },
  crossover: {
    id: 'crossover',
    name: 'Killer Crossover',
    blurb: 'Breaks ankles off the bounce: +2 playmaking, +2 athleticism.',
    selfDelta: { playmaking: 2, athleticism: 2 },
  },
  glove: {
    id: 'glove',
    name: 'The Glove',
    blurb: 'Smothers the wing: +2 perimeter D, and cools the opponent\'s shooting.',
    selfDelta: { perimeterD: 2 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'outside', mult: 0.85, when: 'defense' }],
  },
  chosen_one: {
    id: 'chosen_one',
    name: 'The Chosen One',
    blurb: 'Lifts the whole team on both ends.',
    teamAura: { offenseBonus: 2, defenseBonus: 1, labels: ['The Chosen One'] },
  },
  gravity: {
    id: 'gravity',
    name: 'Gravity',
    blurb: 'Bends the defense: +2 team offense, and pulls help off the rim.',
    teamAura: { offenseBonus: 2, labels: ['Gravity'] },
    hooks: [{ kind: 'opponentRatingMult', stat: 'interiorD', mult: 0.85, when: 'offense' }],
  },
  unguardable: {
    id: 'unguardable',
    name: 'Unguardable',
    blurb: 'Shoots over anyone: +2 outside.',
    selfDelta: { outside: 2 },
  },
  greek_freak: {
    id: 'greek_freak',
    name: 'Freak Athlete',
    blurb: 'Devastating in space: +2 athleticism, and +2 clutch when you run.',
    selfDelta: { athleticism: 2 },
    hooks: [{ kind: 'paceClutch', minPace: 16, clutchAdd: 2 }],
  },
  point_center: {
    id: 'point_center',
    name: 'Point Center',
    blurb: 'A big who runs the offense: +2 playmaking, +2 team offense.',
    selfDelta: { playmaking: 2 },
    teamAura: { offenseBonus: 2, labels: ['Point Center'] },
  },
  step_back: {
    id: 'step_back',
    name: 'Step Back',
    blurb: 'Creates his own shot: +2 outside, +2 IQ.',
    selfDelta: { outside: 2, iq: 2 },
  },
  showtime: {
    id: 'showtime',
    name: 'Showtime',
    blurb: 'Ignites the break: +3 pace and a team offense lift.',
    teamAura: { paceBonus: 3, offenseBonus: 1, labels: ['Showtime'] },
  },
  playoff_jimmy: {
    id: 'playoff_jimmy',
    name: 'Playoff Jimmy',
    blurb: 'Another gear in the fourth: +4 perimeter D, +4 clutch in Q4.',
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { perimeterD: 4, clutch: 4 } }],
  },
  vinsanity: {
    id: 'vinsanity',
    name: 'Vinsanity',
    blurb: 'Plays above the rim: +2 athleticism, +2 outside.',
    selfDelta: { athleticism: 2, outside: 2 },
  },
  mailman: {
    id: 'mailman',
    name: 'The Mailman',
    blurb: 'Always delivers: +2 inside, +2 clutch.',
    selfDelta: { inside: 2, clutch: 2 },
  },
  // --- Expanded curated legend pool (85 new signatures) ---
  jesus_shuttlesworth: {
    id: 'jesus_shuttlesworth',
    name: 'Jesus Shuttlesworth',
    blurb: 'Catch-and-shoot machine: +3 outside, +1 clutch.',
    selfDelta: { outside: 3, clutch: 1 },
  },
  hoodie_melo: {
    id: 'hoodie_melo',
    name: 'Hoodie Melo',
    blurb: 'Pure shot-maker from the wing: +3 outside, +1 inside.',
    selfDelta: { outside: 3, inside: 1 },
  },
  tiny: {
    id: 'tiny',
    name: 'Tiny',
    blurb: 'Scoring point who pushes tempo: +2 playmaking, and +3 pace for the team.',
    selfDelta: { playmaking: 2 },
    teamAura: { paceBonus: 3, labels: ['Tiny'] },
  },
  pitchin_paul: {
    id: 'pitchin_paul',
    name: "Pitchin' Paul",
    blurb: 'Pioneer of the jumper: +2 outside, +2 athleticism.',
    selfDelta: { outside: 2, athleticism: 2 },
  },
  granny_shot: {
    id: 'granny_shot',
    name: 'Granny Shot',
    blurb: 'Automatic at the stripe and on the wing: +2 outside, +2 clutch.',
    selfDelta: { outside: 2, clutch: 2 },
  },
  hang_time: {
    id: 'hang_time',
    name: 'Hang Time',
    blurb: 'Hangs in the air to finish: +2 athleticism, +2 inside.',
    selfDelta: { athleticism: 2, inside: 2 },
  },
  motor_city: {
    id: 'motor_city',
    name: 'Motor City',
    blurb: 'Smooth two-way guard: +2 outside, +2 perimeter D.',
    selfDelta: { outside: 2, perimeterD: 2 },
  },
  hundred_point_night: {
    id: 'hundred_point_night',
    name: '100-Point Night',
    blurb: 'A force of nature in the paint: +3 inside, +3 rebounding, +2 strength.',
    selfDelta: { inside: 3, rebounding: 3, strength: 2 },
  },
  houdini: {
    id: 'houdini',
    name: 'Houdini of the Hardwood',
    blurb: 'Conjures passes from nowhere: +3 playmaking, and a team offense lift.',
    selfDelta: { playmaking: 3 },
    teamAura: { offenseBonus: 1, labels: ['Houdini'] },
  },
  big_redhead: {
    id: 'big_redhead',
    name: 'Big Redhead',
    blurb: 'Relentless energy big: +3 rebounding, +1 interior D.',
    selfDelta: { rebounding: 3, interiorD: 1 },
  },
  kangaroo_kid: {
    id: 'kangaroo_kid',
    name: 'Kangaroo Kid',
    blurb: 'Bouncy do-it-all forward: +2 athleticism, +2 rebounding.',
    selfDelta: { athleticism: 2, rebounding: 2 },
  },
  iron_lung: {
    id: 'iron_lung',
    name: 'Iron Lung',
    blurb: 'Smothers the matchup all night: +3 perimeter D, +1 strength.',
    selfDelta: { perimeterD: 3, strength: 1 },
  },
  doctor_dunk: {
    id: 'doctor_dunk',
    name: 'The Doctor',
    blurb: 'Brings the dunk to the skies: +3 athleticism, +1 inside.',
    selfDelta: { athleticism: 3, inside: 1 },
  },
  clyde_steal: {
    id: 'clyde_steal',
    name: 'Clyde',
    blurb: 'Silky and sticky-fingered: +3 stealing, +1 perimeter D.',
    selfDelta: { stealing: 3, perimeterD: 1 },
  },
  iceman: {
    id: 'iceman',
    name: 'Iceman',
    blurb: 'The finger roll never misses: +3 inside, +1 outside.',
    selfDelta: { inside: 3, outside: 1 },
  },
  midrange_metronome: {
    id: 'midrange_metronome',
    name: 'Midrange Metronome',
    blurb: 'Pull-up jumper on a string: +2 outside, +2 IQ.',
    selfDelta: { outside: 2, iq: 2 },
  },
  the_beard: {
    id: 'the_beard',
    name: 'The Beard',
    blurb: 'Foul-drawing iso maestro: +2 playmaking, and saps the opponent\'s perimeter D.',
    selfDelta: { playmaking: 2 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'perimeterD', mult: 0.85, when: 'offense' }],
  },
  havlicek_stole_it: {
    id: 'havlicek_stole_it',
    name: 'Havlicek Stole It',
    blurb: 'Never stops moving: +2 stealing, +2 athleticism.',
    selfDelta: { stealing: 2, athleticism: 2 },
  },
  the_big_e: {
    id: 'the_big_e',
    name: 'The Big E',
    blurb: 'Workhorse big with a soft touch: +2 inside, +2 rebounding.',
    selfDelta: { inside: 2, rebounding: 2 },
  },
  klaw: {
    id: 'klaw',
    name: 'The Klaw',
    blurb: 'Two-way assassin: +2 perimeter D, +2 stealing, +1 clutch.',
    selfDelta: { perimeterD: 2, stealing: 2, clutch: 1 },
  },
  dr_memory: {
    id: 'dr_memory',
    name: 'Dr. Memory',
    blurb: 'Cerebral glass-cleaner: +3 rebounding, +1 IQ.',
    selfDelta: { rebounding: 3, iq: 1 },
  },
  chairman_boards: {
    id: 'chairman_boards',
    name: 'Chairman of the Boards',
    blurb: 'Owns the offensive glass: +4 rebounding.',
    selfDelta: { rebounding: 4 },
  },
  pistol: {
    id: 'pistol',
    name: 'Pistol',
    blurb: 'Showman with limitless range: +2 outside, +2 playmaking.',
    selfDelta: { outside: 2, playmaking: 2 },
  },
  jump_shooting_big: {
    id: 'jump_shooting_big',
    name: 'Jump-Shooting Big',
    blurb: 'A center who shoots like a guard: +3 outside, +1 inside.',
    selfDelta: { outside: 3, inside: 1 },
  },
  torture_chamber: {
    id: 'torture_chamber',
    name: 'Torture Chamber',
    blurb: 'Endless post moves: +3 inside, and halves your interior D unless you double.',
    selfDelta: { inside: 1 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'interiorD', mult: 0.7, when: 'offense', unlessDoubled: true }],
  },
  mr_basketball: {
    id: 'mr_basketball',
    name: 'Mr. Basketball',
    blurb: 'The original dominant big: +3 inside, +2 rebounding.',
    selfDelta: { inside: 3, rebounding: 2 },
  },
  black_magic: {
    id: 'black_magic',
    name: 'Black Magic',
    blurb: 'Spin moves and flair: +2 inside, +2 athleticism.',
    selfDelta: { inside: 2, athleticism: 2 },
  },
  seven_seconds: {
    id: 'seven_seconds',
    name: 'Seven Seconds',
    blurb: 'Ignites a run-and-gun attack: +3 pace and a team offense lift.',
    teamAura: { paceBonus: 3, offenseBonus: 1, labels: ['Seven Seconds'] },
  },
  one_legged_fade: {
    id: 'one_legged_fade',
    name: 'One-Legged Fade',
    blurb: 'An unblockable fadeaway: +3 outside, +1 inside.',
    selfDelta: { outside: 3, inside: 1 },
  },
  the_chief: {
    id: 'the_chief',
    name: 'The Chief',
    blurb: 'Ageless interior anchor: +2 rebounding, +2 interior D.',
    selfDelta: { rebounding: 2, interiorD: 2 },
  },
  workhorse: {
    id: 'workhorse',
    name: 'Workhorse',
    blurb: 'First superstar scorer: +2 inside, +2 rebounding.',
    selfDelta: { inside: 2, rebounding: 2 },
  },
  the_truth: {
    id: 'the_truth',
    name: 'The Truth',
    blurb: 'Crafty bucket-getter in the clutch: +2 inside, +1 outside, +1 clutch.',
    selfDelta: { inside: 2, outside: 1, clutch: 1 },
  },
  captain_courageous: {
    id: 'captain_courageous',
    name: 'Captain Courageous',
    blurb: 'Wills the team on both ends: +2 strength, and a team defense lift.',
    selfDelta: { strength: 2 },
    teamAura: { defenseBonus: 1, labels: ['Captain'] },
  },
  triple_double_machine: {
    id: 'triple_double_machine',
    name: 'Triple-Double Machine',
    blurb: 'Fills every column: +2 playmaking, +2 rebounding.',
    selfDelta: { playmaking: 2, rebounding: 2 },
  },
  the_admiral: {
    id: 'the_admiral',
    name: 'The Admiral',
    blurb: 'Mobile rim protector: +3 blocking, +1 athleticism.',
    selfDelta: { blocking: 3, athleticism: 1 },
  },
  the_worm: {
    id: 'the_worm',
    name: 'The Worm',
    blurb: 'Lives on the glass and the wing: +5 rebounding, +1 perimeter D.',
    selfDelta: { rebounding: 5, perimeterD: 1 },
  },
  eleven_rings: {
    id: 'eleven_rings',
    name: 'Eleven Rings',
    blurb: 'The ultimate anchor: +4 blocking, +2 interior D, and caps the opponent\'s finishing on D.',
    selfDelta: { blocking: 4, interiorD: 2 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'inside', mult: 0.85, when: 'defense' }],
  },
  iron_man_dolph: {
    id: 'iron_man_dolph',
    name: 'Iron Man',
    blurb: 'Durable two-way forward: +2 rebounding, +2 outside.',
    selfDelta: { rebounding: 2, outside: 2 },
  },
  free_throw_king: {
    id: 'free_throw_king',
    name: 'Free-Throw King',
    blurb: 'Deadeye from anywhere: +2 outside, +2 clutch.',
    selfDelta: { outside: 2, clutch: 2 },
  },
  floor_general: {
    id: 'floor_general',
    name: 'Floor General',
    blurb: 'Runs a flawless offense: +3 playmaking, and a team offense lift.',
    selfDelta: { playmaking: 3 },
    teamAura: { offenseBonus: 1, labels: ['Pick & Roll'] },
  },
  nate_the_great: {
    id: 'nate_the_great',
    name: 'Nate the Great',
    blurb: 'Premier interior wall: +3 blocking, +1 rebounding.',
    selfDelta: { blocking: 3, rebounding: 1 },
  },
  outlet_cannon: {
    id: 'outlet_cannon',
    name: 'Outlet Cannon',
    blurb: 'Rebounds and fires the break: +3 rebounding, and a team pace lift.',
    selfDelta: { rebounding: 3 },
    teamAura: { paceBonus: 1, labels: ['Outlet'] },
  },
  flash: {
    id: 'flash',
    name: 'Flash',
    blurb: 'Another gear in the fourth: +2 inside, then +3 inside and +3 clutch in Q4.',
    selfDelta: { inside: 2 },
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { inside: 3, clutch: 3 } }],
  },
  redwood: {
    id: 'redwood',
    name: 'Redwood',
    blurb: 'Passing big who blocks shots: +2 blocking, +2 playmaking.',
    selfDelta: { blocking: 2, playmaking: 2 },
  },
  mr_clutch: {
    id: 'mr_clutch',
    name: 'Mr. Clutch',
    blurb: 'The logo rises late: +2 outside, then +4 clutch in Q4.',
    selfDelta: { outside: 2 },
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { clutch: 4 } }],
  },
  brodie: {
    id: 'brodie',
    name: 'Brodie',
    blurb: 'A triple-double engine in transition: +2 athleticism, and +2 clutch when you run.',
    selfDelta: { athleticism: 2 },
    hooks: [{ kind: 'paceClutch', minPace: 16, clutchAdd: 2 }],
  },
  big_game_james: {
    id: 'big_game_james',
    name: 'Big Game James',
    blurb: 'Saves his best for the biggest stage: +2 inside, then +3 inside in Q4.',
    selfDelta: { inside: 2 },
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { inside: 3 } }],
  },
  uncle_drew: {
    id: 'uncle_drew',
    name: 'Uncle Drew',
    blurb: 'The best handle ever: +2 playmaking, +2 inside.',
    selfDelta: { playmaking: 2, inside: 2 },
  },
  pandemic_p: {
    id: 'pandemic_p',
    name: 'Two-Way Forward',
    blurb: 'Long, switchable wing: +2 perimeter D, +1 outside, +1 stealing.',
    selfDelta: { perimeterD: 2, outside: 1, stealing: 1 },
  },
  splash_brother: {
    id: 'splash_brother',
    name: 'Splash Brother',
    blurb: 'Catch-and-shoot lightning: +3 outside, +1 perimeter D.',
    selfDelta: { outside: 3, perimeterD: 1 },
  },
  defensive_qb: {
    id: 'defensive_qb',
    name: 'Defensive QB',
    blurb: 'Quarterbacks the defense: +2 IQ, and a team defense lift.',
    selfDelta: { iq: 2 },
    teamAura: { defenseBonus: 2, labels: ['Defensive QB'] },
  },
  ant_man: {
    id: 'ant_man',
    name: 'Ant-Man',
    blurb: 'Explosive rising star: +2 athleticism, +2 outside.',
    selfDelta: { athleticism: 2, outside: 2 },
  },
  the_alien: {
    id: 'the_alien',
    name: 'The Alien',
    blurb: 'Eight feet of rim protection: +4 blocking, +1 outside, +1 rebounding.',
    selfDelta: { blocking: 4, outside: 1, rebounding: 1 },
  },
  spida: {
    id: 'spida',
    name: 'Spida',
    blurb: 'Bouncy three-level scorer: +2 outside, +2 athleticism.',
    selfDelta: { outside: 2, athleticism: 2 },
  },
  two_way_wing: {
    id: 'two_way_wing',
    name: 'Two-Way Wing',
    blurb: 'Scores and defends the wing: +2 outside, +2 perimeter D.',
    selfDelta: { outside: 2, perimeterD: 2 },
  },
  ice_trae: {
    id: 'ice_trae',
    name: 'Ice Trae',
    blurb: 'Deep range and silences the crowd: +3 outside, +1 playmaking.',
    selfDelta: { outside: 3, playmaking: 1 },
  },
  pace_and_space: {
    id: 'pace_and_space',
    name: 'Pace and Space',
    blurb: 'Pushes the tempo and finds shooters: +2 pace, +1 offense, +1 playmaking.',
    selfDelta: { playmaking: 1 },
    teamAura: { paceBonus: 2, offenseBonus: 1, labels: ['Pace & Space'] },
  },
  handoff_hub: {
    id: 'handoff_hub',
    name: 'Handoff Hub',
    blurb: 'Offensive fulcrum at the elbow: +2 playmaking, +2 rebounding.',
    selfDelta: { playmaking: 2, rebounding: 2 },
  },
  switch_everything: {
    id: 'switch_everything',
    name: 'Switch Everything',
    blurb: 'Guards one through five: +2 perimeter D, +2 interior D.',
    selfDelta: { perimeterD: 2, interiorD: 2 },
  },
  point_of_attack: {
    id: 'point_of_attack',
    name: 'Point of Attack',
    blurb: 'Hounds the ball-handler: +2 perimeter D, +2 stealing.',
    selfDelta: { perimeterD: 2, stealing: 2 },
  },
  the_stifle_tower: {
    id: 'the_stifle_tower',
    name: 'The Stifle Tower',
    blurb: 'Walls off the rim: +4 blocking, +1 interior D, and caps the opponent\'s finishing on D.',
    selfDelta: { blocking: 4, interiorD: 1 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'inside', mult: 0.85, when: 'defense' }],
  },
  midrange_assassin: {
    id: 'midrange_assassin',
    name: 'Midrange Assassin',
    blurb: 'Throwback bucket-getter: +2 inside, +1 outside, +1 clutch.',
    selfDelta: { inside: 2, outside: 1, clutch: 1 },
  },
  spicy_p: {
    id: 'spicy_p',
    name: 'Spicy P',
    blurb: 'Versatile two-way forward: +2 inside, +2 athleticism.',
    selfDelta: { inside: 2, athleticism: 2 },
  },
  silky_smooth: {
    id: 'silky_smooth',
    name: 'Silky Smooth',
    blurb: 'Effortless three-level scorer: +3 outside, +1 inside.',
    selfDelta: { outside: 3, inside: 1 },
  },
  stretch_five: {
    id: 'stretch_five',
    name: 'Stretch Five',
    blurb: 'A center who spaces the floor: +3 outside, +1 rebounding.',
    selfDelta: { outside: 3, rebounding: 1 },
  },
  blue_arrow: {
    id: 'blue_arrow',
    name: 'Blue Arrow',
    blurb: 'Playoff riser with deep range: +2 outside, then +3 outside in Q4.',
    selfDelta: { outside: 2 },
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { outside: 3 } }],
  },
  the_unicorn: {
    id: 'the_unicorn',
    name: 'The Unicorn',
    blurb: 'Shoots threes and swats shots: +2 outside, +2 blocking.',
    selfDelta: { outside: 2, blocking: 2 },
  },
  hangtime_lavine: {
    id: 'hangtime_lavine',
    name: 'Hangtime',
    blurb: 'Highlight-reel leaper: +2 athleticism, +2 outside.',
    selfDelta: { athleticism: 2, outside: 2 },
  },
  help_side_eraser: {
    id: 'help_side_eraser',
    name: 'Help-Side Eraser',
    blurb: 'Rotates over to swat shots: +3 blocking, +1 athleticism.',
    selfDelta: { blocking: 3, athleticism: 1 },
  },
  downhill_freight: {
    id: 'downhill_freight',
    name: 'Downhill Freight',
    blurb: 'Bullies a path to the rim: +2 strength, +2 inside.',
    selfDelta: { strength: 2, inside: 2 },
  },
  turbo: {
    id: 'turbo',
    name: 'Turbo',
    blurb: 'Blazing end-to-end speed: +2 athleticism, and a team pace lift.',
    selfDelta: { athleticism: 2 },
    teamAura: { paceBonus: 2, labels: ['Turbo'] },
  },
  euro_step: {
    id: 'euro_step',
    name: 'Euro Step',
    blurb: 'Crafty sixth-man spark: +2 inside, +2 playmaking.',
    selfDelta: { inside: 2, playmaking: 2 },
  },
  teardrop: {
    id: 'teardrop',
    name: 'Teardrop',
    blurb: 'Floats it over the bigs: +2 inside, +2 athleticism.',
    selfDelta: { inside: 2, athleticism: 2 },
  },
  high_low_maestro: {
    id: 'high_low_maestro',
    name: 'High-Low Maestro',
    blurb: 'Skilled passing big: +2 playmaking, +2 inside.',
    selfDelta: { playmaking: 2, inside: 2 },
  },
  superman_dwight: {
    id: 'superman_dwight',
    name: 'Superman',
    blurb: 'Elite athlete center: +3 blocking, +1 rebounding.',
    selfDelta: { blocking: 3, rebounding: 1 },
  },
  great_wall: {
    id: 'great_wall',
    name: 'The Great Wall',
    blurb: 'A skyscraper in the paint: +3 inside, +2 blocking.',
    selfDelta: { inside: 3, blocking: 2 },
  },
  big_ben: {
    id: 'big_ben',
    name: 'Big Ben',
    blurb: 'Undersized defensive monster: +3 rebounding, +2 blocking.',
    selfDelta: { rebounding: 3, blocking: 2 },
  },
  mr_big_shot: {
    id: 'mr_big_shot',
    name: 'Mr. Big Shot',
    blurb: 'Steady hand in crunch time: +2 outside, +2 clutch.',
    selfDelta: { outside: 2, clutch: 2 },
  },
  bucket_getter: {
    id: 'bucket_getter',
    name: 'Bucket Getter',
    blurb: 'Unstoppable mid-post scorer: +3 inside, +1 outside.',
    selfDelta: { inside: 3, outside: 1 },
  },
  crafty_captain: {
    id: 'crafty_captain',
    name: 'Crafty Captain',
    blurb: 'Footwork and floaters in the clutch: +2 inside, +2 clutch.',
    selfDelta: { inside: 2, clutch: 2 },
  },
  iron_man_wing: {
    id: 'iron_man_wing',
    name: 'Iron Man',
    blurb: 'Never misses a game, never rests on D: +3 perimeter D, +1 stealing.',
    selfDelta: { perimeterD: 3, stealing: 1 },
  },
  rim_spider: {
    id: 'rim_spider',
    name: 'Rim Spider',
    blurb: 'Long-armed shot-blocker: +3 blocking, +1 outside.',
    selfDelta: { blocking: 3, outside: 1 },
  },
  swipa: {
    id: 'swipa',
    name: 'Swipa',
    blurb: 'Blinding speed and quick hands: +2 stealing, +2 athleticism.',
    selfDelta: { stealing: 2, athleticism: 2 },
  },
  // --- Unique signature abilities (one nickname per legend) ---
  dream_shake: {
    id: 'dream_shake',
    name: 'Dream Shake',
    blurb: 'Dizzying post footwork: +3 inside, and halves your interior D unless you double.',
    selfDelta: { inside: 3 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'interiorD', mult: 0.5, when: 'offense', unlessDoubled: true }],
  },
  the_brow: {
    id: 'the_brow',
    name: 'The Brow',
    blurb: 'Erases shots at the rim: +4 blocking, +1 interior D, and caps the opponent\'s finishing on D.',
    selfDelta: { blocking: 4, interiorD: 1 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'inside', mult: 0.85, when: 'defense' }],
  },
  big_ticket: {
    id: 'big_ticket',
    name: 'Big Ticket',
    blurb: 'Ferocious defensive intensity: +2 interior D, +2 blocking, and a team defense lift.',
    selfDelta: { interiorD: 2, blocking: 2 },
    teamAura: { defenseBonus: 1, labels: ['Big Ticket'] },
  },
  ewing_anchor: {
    id: 'ewing_anchor',
    name: 'Bridgeman',
    blurb: 'Towering two-way center: +3 blocking, +2 inside.',
    selfDelta: { blocking: 3, inside: 2 },
  },
  the_process: {
    id: 'the_process',
    name: 'The Process',
    blurb: 'Dominant two-way big: +2 inside, +2 blocking, and a team defense lift.',
    selfDelta: { inside: 2, blocking: 2 },
    teamAura: { defenseBonus: 1, labels: ['The Process'] },
  },
  shot_creator: {
    id: 'shot_creator',
    name: 'Shot Creator',
    blurb: 'Generates a clean look from anywhere: +2 outside, +2 inside, +1 clutch.',
    selfDelta: { outside: 2, inside: 2, clutch: 1 },
  },
  human_highlight: {
    id: 'human_highlight',
    name: 'Human Highlight',
    blurb: 'Explosive above-the-rim scorer: +3 athleticism, +2 inside.',
    selfDelta: { athleticism: 3, inside: 2 },
  },
  tmac_iso: {
    id: 'tmac_iso',
    name: 'Iso Maestro',
    blurb: 'Unstoppable in isolation: +2 outside, +2 inside, and saps the opponent\'s perimeter D.',
    selfDelta: { outside: 2, inside: 2 },
    hooks: [{ kind: 'opponentRatingMult', stat: 'perimeterD', mult: 0.85, when: 'offense' }],
  },
  be_legendary: {
    id: 'be_legendary',
    name: 'Be Legendary',
    blurb: 'A pure three-level scorer: +3 outside, +2 inside.',
    selfDelta: { outside: 3, inside: 2 },
  },
  deadeye_price: {
    id: 'deadeye_price',
    name: 'Deadeye',
    blurb: 'Pinpoint sharpshooter from deep: +4 outside, +1 playmaking.',
    selfDelta: { outside: 4, playmaking: 1 },
  },
  miller_time: {
    id: 'miller_time',
    name: 'Miller Time',
    blurb: 'Rains threes in crunch time: +2 outside, then +5 outside in the fourth.',
    selfDelta: { outside: 2 },
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { outside: 5 } }],
  },
  triple_double_kidd: {
    id: 'triple_double_kidd',
    name: 'Stat Sheet Stuffer',
    blurb: 'Orchestrates and rebounds it all: +3 playmaking, +2 rebounding, and a team offense lift.',
    selfDelta: { playmaking: 3, rebounding: 2 },
    teamAura: { offenseBonus: 1, labels: ['Triple-Double'] },
  },
  point_forward: {
    id: 'point_forward',
    name: 'Point Forward',
    blurb: 'A big who runs the break: +3 playmaking, +2 inside.',
    selfDelta: { playmaking: 3, inside: 2 },
  },
  ja_liftoff: {
    id: 'ja_liftoff',
    name: 'Liftoff',
    blurb: 'Explosive athletic finisher: +3 athleticism, +2 inside.',
    selfDelta: { athleticism: 3, inside: 2 },
  },
  grandmama: {
    id: 'grandmama',
    name: 'Grandmama',
    blurb: 'Bullying power scorer: +2 strength, +2 inside, +1 outside.',
    selfDelta: { strength: 2, inside: 2, outside: 1 },
  },
  zion_force: {
    id: 'zion_force',
    name: 'Force of Nature',
    blurb: 'Explosive interior force: +2 strength, +2 inside, +1 athleticism.',
    selfDelta: { strength: 2, inside: 2, athleticism: 1 },
  },
  the_glide: {
    id: 'the_glide',
    name: 'The Glide',
    blurb: 'Soaring all-around wing: +2 athleticism, +2 inside, +1 stealing.',
    selfDelta: { athleticism: 2, inside: 2, stealing: 1 },
  },
  midrange_maestro: {
    id: 'midrange_maestro',
    name: 'Midrange Maestro',
    blurb: 'Silky pull-up artist: +2 inside, +2 outside, +1 clutch.',
    selfDelta: { inside: 2, outside: 2, clutch: 1 },
  },
  agent_zero: {
    id: 'agent_zero',
    name: 'Agent Zero',
    blurb: 'Fearless volume scorer: +3 outside, then +3 outside in the fourth.',
    selfDelta: { outside: 3 },
    hooks: [{ kind: 'quarterDelta', quarter: 4, delta: { outside: 3 } }],
  },
  zeke: {
    id: 'zeke',
    name: 'Zeke',
    blurb: 'Crafty lead guard: +2 playmaking, +2 inside, +1 stealing.',
    selfDelta: { playmaking: 2, inside: 2, stealing: 1 },
  },
  point_god: {
    id: 'point_god',
    name: 'Point God',
    blurb: 'Surgical floor general: +3 playmaking, +2 stealing, and a team offense lift.',
    selfDelta: { playmaking: 3, stealing: 2 },
    teamAura: { offenseBonus: 1, labels: ['Point God'] },
  },
  pippen_lockdown: {
    id: 'pippen_lockdown',
    name: 'Two-Way Terror',
    blurb: 'Elite two-way wing: +2 perimeter D, +2 stealing, +1 athleticism.',
    selfDelta: { perimeterD: 2, stealing: 2, athleticism: 1 },
  },
};

/** Look up an ability by id (undefined for non-legends or unknown ids). */
export function getAbility(id?: string): Ability | undefined {
  return id ? ABILITIES[id] : undefined;
}
