import { hashSeed } from './rng';
import type { ImageSourcePropType } from 'react-native';

// Silhouette images generated at build time: sil-0.png through sil-19.png
// These are deterministic pixel art silhouettes for fake/generated players.

/**
 * Map of silhouette image keys to their require()-backed sources.
 * Auto-generated by scripts/generate-silhouette.ts.
 * Import from the manifest file.
 */
import { SILHOUETTES } from '@/assets/playerImages';

/**
 * Return a silhouette image for a player name, or null if none available.
 * Uses FNV-1a hash of the name to deterministically select one of 20 silhouettes.
 * Same name always produces the same silhouette.
 */
export function silhouetteFor(name: string): ImageSourcePropType | null {
  const idx = hashSeed(name) % 20;
  const key = `sil-${idx}`;
  return SILHOUETTES[key] ?? null;
}
