import { hashSeed } from './rng';
import type { ImageSourcePropType } from 'react-native';

// Silhouette images generated at build time:
// - sil-0.png through sil-19.png: procedural pixel art for fake/generated players
// - enr-{slug}.png: enhanced headshot-based silhouettes with facial features

/**
 * Map of procedural silhouette image keys to their require()-backed sources.
 * Auto-generated by scripts/generate-silhouette.ts.
 */
import { SILHOUETTES } from '@/assets/playerImages';

/**
 * Map of enhanced silhouette image keys to their require()-backed sources.
 * Auto-generated by scripts/generate-manifest.ts from enr-*.png files.
 */
import { ENHANCED_SILHOUETTES } from '@/assets/playerImages';

/**
 * Return a silhouette image for a player slug, or null if none available.
 *
 * Lookup order:
 * 1. Enhanced silhouette (enr-{slug}) — headshot-based with facial features
 * 2. Procedural silhouette (sil-N) — hash-based fallback for generated players
 * 3. null — no silhouette available
 *
 * Same slug always produces the same silhouette.
 */
export function silhouetteFor(slug: string): ImageSourcePropType | null {
  // Try enhanced silhouette first (real player headshots)
  const enhancedKey = `enr-${slug}`;
  if (enhancedKey in ENHANCED_SILHOUETTES) {
    return ENHANCED_SILHOUETTES[enhancedKey];
  }

  // Fall back to procedural silhouette (generated players)
  const idx = hashSeed(slug) % 20;
  const key = `sil-${idx}`;
  return SILHOUETTES[key] ?? null;
}
