// AUTO-GENERATED by scripts/generate-sfx.ts. Do not edit by hand.
// Static require() map of the baked chiptune music beds. Regenerate with: npm run gen:sfx

export const MUSIC_SOURCES = {
  menuTheme: require('../../assets/audio/music_menuTheme.wav'),
  runThemeA: require('../../assets/audio/music_runThemeA.wav'),
  runThemeB: require('../../assets/audio/music_runThemeB.wav'),
  gameEnergy: require('../../assets/audio/music_gameEnergy.wav'),
};

export type MusicName = keyof typeof MUSIC_SOURCES;
