// AUTO-GENERATED by scripts/generate-sfx.ts. Do not edit by hand.
// Static require() map of the baked chiptune music beds. Regenerate with: npm run gen:sfx

export const MUSIC_SOURCES = {
  menuLoop: require('../../assets/audio/music_menuLoop.wav'),
  gameLoop: require('../../assets/audio/music_gameLoop.wav'),
};

export type MusicName = keyof typeof MUSIC_SOURCES;
