#!/usr/bin/env tsx
// Auto-generates src/assets/playerImages.ts from the actual PNG files on disk.
// Run: npx tsx scripts/generate-manifest.ts
//
// File naming conventions:
//   sil-*.png   → procedural pixel-art silhouettes (fallback for generated players)
//   enr-*.png   → enhanced headshot-based silhouettes (with facial features)
//   others      → player headshots

import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const PLAYER_IMAGES_DIR = join(__dirname, '..', 'assets', 'player-images');
const MANIFEST_PATH = join(__dirname, '..', 'src', 'assets', 'playerImages.ts');

function generateManifest(): string {
  const files = readdirSync(PLAYER_IMAGES_DIR).sort();

  const silhouettes: [string, string][] = [];
  const enhancedSilhouettes: [string, string][] = [];
  const headshots: [string, string][] = [];

  for (const file of files) {
    if (!file.endsWith('.png')) continue;
    const slug = file.replace('.png', '');

    if (slug.startsWith('sil-')) {
      silhouettes.push([slug, slug]);
    } else if (slug.startsWith('enr-')) {
      enhancedSilhouettes.push([slug, slug]);
    } else {
      headshots.push([slug, slug]);
    }
  }

  // Build require lines
  const headshotLines = headshots
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([slug]) => `  '${slug}': require('../../assets/player-images/${slug}.png'),`);

  const silhouetteLines = silhouettes
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([slug]) => `  '${slug}': require('../../assets/player-images/${slug}.png'),`);

  const enhancedLines = enhancedSilhouettes
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([slug]) => `  '${slug}': require('../../assets/player-images/${slug}.png'),`);

  return [
    '// AUTO-GENERATED by scripts/generate-manifest.ts. Do not edit by hand.',
    '// Maps player slugs and silhouette indices to their baked PNG assets.',
    '',
    "import type { ImageSourcePropType } from 'react-native';",
    '',
    'export const PLAYER_HEADSHOTS: Record<string, ImageSourcePropType> = {',
    ...headshotLines,
    '};',
    '',
    'export const ENHANCED_SILHOUETTES: Record<string, ImageSourcePropType> = {',
    ...enhancedLines,
    '};',
    '',
    'export const SILHOUETTES: Record<string, ImageSourcePropType> = {',
    ...silhouetteLines,
    '};',
    '',
  ].join('\n');
}

const content = generateManifest();
writeFileSync(MANIFEST_PATH, content, 'utf-8');
console.log(`Generated ${MANIFEST_PATH}`);
