/**
 * Offline chiptune SFX baker. Renders every recipe in src/audio/recipes.ts to a small
 * 16-bit PCM WAV under assets/audio, and writes the static require() manifest at
 * src/audio/sfxManifest.ts. The app NEVER synthesizes at runtime: it bundles the
 * committed .wav files, so audio stays offline and deterministic.
 *
 *   npx tsx scripts/generate-sfx.ts        (or: npm run gen:sfx)
 *
 * Run-once-occasionally (like fetch:nba / pixelate:logos). Commit BOTH the generated
 * assets/audio/*.wav and src/audio/sfxManifest.ts so CI builds without ever running it.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodeWav } from '../src/audio/wav';
import { renderRecipe } from '../src/audio/synth';
import { RECIPES } from '../src/audio/recipes';

type Name = keyof typeof RECIPES;

const here = dirname(fileURLToPath(import.meta.url));
const audioDir = join(here, '..', 'assets', 'audio');
const manifestPath = join(here, '..', 'src', 'audio', 'sfxManifest.ts');

function writeManifest(names: Name[]): void {
  const sources = names.map((n) => `  ${n}: require('../../assets/audio/${n}.wav'),`).join('\n');
  const pools = names.map((n) => `  ${n}: ${RECIPES[n].pool},`).join('\n');
  const body =
    `// AUTO-GENERATED by scripts/generate-sfx.ts. Do not edit by hand.\n` +
    `// Static require() map of the baked chiptune SFX, plus each sound's runtime\n` +
    `// round-robin pool size. Regenerate with: npm run gen:sfx\n\n` +
    `export const SFX_SOURCES = {\n${sources}\n};\n\n` +
    `export type SfxName = keyof typeof SFX_SOURCES;\n\n` +
    `export const SFX_POOL: Record<SfxName, number> = {\n${pools}\n};\n`;
  writeFileSync(manifestPath, body);
}

function main(): void {
  mkdirSync(audioDir, { recursive: true });
  const names = Object.keys(RECIPES) as Name[];
  for (const name of names) {
    const samples = renderRecipe(RECIPES[name]);
    writeFileSync(join(audioDir, `${name}.wav`), encodeWav(samples));
    console.log(`ok   ${name}.wav  (${samples.length} samples)`);
  }
  writeManifest(names);
  console.log(`\nWrote ${names.length} WAVs to ${audioDir}`);
  console.log(`Wrote manifest ${manifestPath}`);
}

main();
