/**
 * Offline chiptune audio baker. Renders every SFX recipe (src/audio/recipes.ts) and every
 * music bed (src/audio/musicTracks.ts) to small 16-bit PCM WAVs under assets/audio, and
 * writes the static require() manifests (src/audio/sfxManifest.ts, src/audio/musicManifest.ts).
 * The app NEVER synthesizes at runtime: it bundles the committed .wav files, so audio stays
 * offline and deterministic.
 *
 *   npx tsx scripts/generate-sfx.ts        (or: npm run gen:sfx)
 *
 * Run-once-occasionally (like fetch:nba / pixelate:logos). Commit BOTH the generated
 * assets/audio/*.wav and the manifests so CI builds without ever running this script.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodeWav, encodeWavStereo, MUSIC_SAMPLE_RATE } from '../src/audio/wav';
import { renderRecipe } from '../src/audio/synth';
import { RECIPES } from '../src/audio/recipes';
import { renderMusicLoop } from '../src/audio/sequencer';
import { MUSIC_TRACKS } from '../src/audio/musicTracks';

type Name = keyof typeof RECIPES;
type MusicName = keyof typeof MUSIC_TRACKS;

const here = dirname(fileURLToPath(import.meta.url));
const audioDir = join(here, '..', 'assets', 'audio');
const manifestPath = join(here, '..', 'src', 'audio', 'sfxManifest.ts');
const musicManifestPath = join(here, '..', 'src', 'audio', 'musicManifest.ts');

function writeManifest(names: Name[]): void {
  const sources = names.map((n) => `  ${n}: require('../../assets/audio/${n}.wav'),`).join('\n');
  const pools = names.map((n) => `  ${n}: ${RECIPES[n].pool},`).join('\n');
  const body =
    `// AUTO-GENERATED by scripts/generate-sfx.ts. Do not edit by hand.\n` +
    `// Static require() map of the baked chiptune SFX, plus each sound's runtime\n` +
    `// round-robin pool size. Regenerate with: npm run gen:sfx\n\n` +
    `export const SFX_SOURCES = {\n${sources}\n};\n\n` +
    `export type SfxName = keyof typeof SFX_SOURCES;\n\n` +
    `export const SFX_POOL: Record<SfxName, number> = {\n${pools}\n};\n`;
  writeFileSync(manifestPath, body);
}

function writeMusicManifest(names: MusicName[]): void {
  const sources = names
    .map((n) => `  ${n}: require('../../assets/audio/music_${n}.wav'),`)
    .join('\n');
  const body =
    `// AUTO-GENERATED by scripts/generate-sfx.ts. Do not edit by hand.\n` +
    `// Static require() map of the baked chiptune music beds. Regenerate with: npm run gen:sfx\n\n` +
    `export const MUSIC_SOURCES = {\n${sources}\n};\n\n` +
    `export type MusicName = keyof typeof MUSIC_SOURCES;\n`;
  writeFileSync(musicManifestPath, body);
}

/** Peak and RMS in dBFS, so loudness parity across bakes is a printed fact. */
function levels(...channels: Float32Array[]): string {
  let peak = 0;
  let sumSquares = 0;
  let count = 0;
  for (const channel of channels) {
    for (const sample of channel) {
      peak = Math.max(peak, Math.abs(sample));
      sumSquares += sample * sample;
    }
    count += channel.length;
  }
  const db = (v: number) => (v > 0 ? (20 * Math.log10(v)).toFixed(1) : '-inf');
  return `peak ${db(peak)} dBFS, rms ${db(Math.sqrt(sumSquares / count))} dBFS`;
}

function main(): void {
  mkdirSync(audioDir, { recursive: true });

  const names = Object.keys(RECIPES) as Name[];
  for (const name of names) {
    const samples = renderRecipe(RECIPES[name]);
    writeFileSync(join(audioDir, `${name}.wav`), encodeWav(samples));
    console.log(`ok   ${name}.wav  (${samples.length} samples, ${levels(samples)})`);
  }
  writeManifest(names);

  const musicNames = Object.keys(MUSIC_TRACKS) as MusicName[];
  for (const name of musicNames) {
    const { left, right } = renderMusicLoop(MUSIC_TRACKS[name]);
    const wav = encodeWavStereo(left, right, MUSIC_SAMPLE_RATE);
    writeFileSync(join(audioDir, `music_${name}.wav`), wav);
    const seconds = (left.length / MUSIC_SAMPLE_RATE).toFixed(1);
    const mb = (wav.length / 1024 / 1024).toFixed(2);
    console.log(`ok   music_${name}.wav  (${seconds}s stereo, ${mb} MB, ${levels(left, right)})`);
  }
  writeMusicManifest(musicNames);

  console.log(`\nWrote ${names.length} SFX + ${musicNames.length} music WAVs to ${audioDir}`);
  console.log(`Wrote manifests ${manifestPath} and ${musicManifestPath}`);
}

main();
