/**
 * Offline team-logo pixelizer. Downloads each franchise's logo from ESPN's public
 * CDN and bakes it into a small, hard-edged 8-bit PNG under assets/logos, plus a
 * static require() manifest at src/assets/teamLogos.ts. The app NEVER fetches at
 * runtime: it bundles the committed PNGs, so the map stays offline and deterministic.
 *
 *   npx tsx scripts/pixelate-logos.ts
 *
 * Run-once-occasionally (like fetch:nba). Commit BOTH the generated assets/logos/*.png
 * and src/assets/teamLogos.ts so CI builds without ever running this script.
 *
 * Pipeline per team: fetch the ~500px transparent PNG -> autocrop the transparent
 * border -> contain into a GRID box -> posterize for chunky 8-bit color banding ->
 * binarize the alpha (kills the anti-aliased halo so pixels read as hard blocks) ->
 * upscale nearest-neighbor so the stored PNG has crisp square pixels that survive
 * React Native's bilinear downscale on the map tile.
 *
 * Logo source: a.espncdn.com/i/teamlogos/nba/500/{espn}.png. ESPN's slug differs
 * from our 3-letter abbreviation for a handful of teams (see ESPN_ABBR), so the
 * output is keyed by OUR abbreviation and the manifest matches src/data/nba-teams.json.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Jimp, ResizeStrategy } from 'jimp';
import teams from '../src/data/nba-teams.json';

type Team = { name: string; city: string; abbreviation: string };

/** Our 3-letter abbreviation -> ESPN logo slug. Most are the lowercased abbr; the
 * teams whose ESPN slug differs are spelled out. Every team must have an entry. */
const ESPN_ABBR: Record<string, string> = {
  ATL: 'atl', BOS: 'bos', BKN: 'bkn', CHA: 'cha', CHI: 'chi',
  CLE: 'cle', DAL: 'dal', DEN: 'den', DET: 'det', GSW: 'gs',
  HOU: 'hou', IND: 'ind', LAC: 'lac', LAL: 'lal', MEM: 'mem',
  MIA: 'mia', MIL: 'mil', MIN: 'min', NOP: 'no', NYK: 'ny',
  OKC: 'okc', ORL: 'orl', PHI: 'phi', PHX: 'phx', POR: 'por',
  SAC: 'sac', SAS: 'sa', TOR: 'tor', UTA: 'utah', WAS: 'wsh',
};

const GRID = 24; // logical pixel grid the logo is reduced to (chunky 8-bit blocks)
const SCALE = 8; // nearest-neighbor upscale so stored pixels are crisp blocks
const OUT_PX = GRID * SCALE; // 192px stored PNG
const POSTERIZE_LEVELS = 4; // color levels per channel: fewer bands reads more arcade
const ALPHA_CUTOFF = 128; // alpha >= this becomes opaque, below becomes clear

const here = dirname(fileURLToPath(import.meta.url));
const logosDir = join(here, '..', 'assets', 'logos');
const manifestPath = join(here, '..', 'src', 'assets', 'teamLogos.ts');

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function pixelateOne(projAbbr: string, espn: string): Promise<void> {
  const url = `https://a.espncdn.com/i/teamlogos/nba/500/${espn}.png`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${espn}: HTTP ${res.status} ${res.statusText}`);
  const img = await Jimp.fromBuffer(Buffer.from(await res.arrayBuffer()));

  // 1. Trim the transparent border so every logo fills its grid consistently.
  img.autocrop();
  // 2. Fit (preserving aspect) into the small pixel grid, padded transparent.
  img.contain({ w: GRID, h: GRID });
  // 3. Quantize color to a few levels per channel for the 8-bit look.
  img.posterize(POSTERIZE_LEVELS);
  // 4. Binarize alpha: drop the soft AA fringe so the logo reads as hard pixels.
  img.scan(0, 0, img.width, img.height, (_x, _y, idx) => {
    const a = img.bitmap.data[idx + 3];
    img.bitmap.data[idx + 3] = a < ALPHA_CUTOFF ? 0 : 255;
  });
  // 5. Upscale with nearest neighbor so each logical pixel is a solid block.
  img.resize({ w: OUT_PX, h: OUT_PX, mode: ResizeStrategy.NEAREST_NEIGHBOR });

  mkdirSync(logosDir, { recursive: true });
  await img.write(join(logosDir, `${projAbbr}.png`) as `${string}.png`);
}

function writeManifest(abbrs: string[]): void {
  const lines = abbrs.map(
    (abbr) => `  ${abbr}: require('../../assets/logos/${abbr}.png'),`
  );
  const body =
    `// AUTO-GENERATED by scripts/pixelate-logos.ts. Do not edit by hand.\n` +
    `// 8-bit pixelations of each franchise logo, keyed by our 3-letter abbreviation.\n` +
    `import type { ImageSourcePropType } from 'react-native';\n\n` +
    `export const TEAM_LOGOS: Record<string, ImageSourcePropType> = {\n` +
    lines.join('\n') +
    `\n};\n`;
  mkdirSync(dirname(manifestPath), { recursive: true });
  writeFileSync(manifestPath, body);
}

async function main(): Promise<void> {
  const list = teams as Team[];
  const missing = list.filter((t) => !ESPN_ABBR[t.abbreviation]);
  if (missing.length) {
    throw new Error(`No ESPN slug for: ${missing.map((t) => t.abbreviation).join(', ')}`);
  }

  const done: string[] = [];
  for (const t of list) {
    const espn = ESPN_ABBR[t.abbreviation];
    try {
      await pixelateOne(t.abbreviation, espn);
      done.push(t.abbreviation);
      console.log(`ok   ${t.abbreviation} <- ${espn}`);
    } catch (err) {
      console.error(`FAIL ${t.abbreviation} <- ${espn}: ${(err as Error).message}`);
    }
    await sleep(250); // be polite to the CDN across 30 sequential fetches
  }

  // Only enumerate the logos that actually baked, so a missing fetch never points
  // the manifest at a file that does not exist.
  writeManifest(done.sort());
  console.log(`\nWrote ${done.length}/${list.length} logos to ${logosDir}`);
  console.log(`Wrote manifest ${manifestPath}`);
  if (done.length !== list.length) {
    console.warn('Some logos failed; re-run to retry the missing teams.');
  }
}

void main();
